python3-dtc: switch to setuptools3
Issue: LINUXEXEC-23251 LINUXEXEC-6644

Fixes:
  ERROR: ParseError at /build/layers/meta-xilinx/meta-xilinx-core/recipes-kernel/dtc/python3-dtc_1.6.0.bb:20: Could not inherit file classes/distutils3.bbclass

(master rev: 80f5187f7504b7c5c52e017daa98cbe0c7d944dd)

Signed-off-by: Mingli Yu <mingli.yu@windriver.com>