meta-xlinx-core: mask virtualization layer
Issue: LINCD-8443

Because of meta-xilinx commit 81616c60 ("lopper: move to bbappend,
remove obsolete items"), lopper is now provided in meta-virtualization,
since we don't support virtualization, mask this layer to eliminate
the error as below:

ERROR: No recipes in default available for:
layers/meta-xilinx/meta-xilinx-core/dynamic-layers/virtualization-layer/recipes-kernel/lopper/lopper.bbappend

(LOCAL REV: NOT UPSTREAM) - WRLinux specific

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>