mesa-demos: fix build error by deleting undeclared EGL_PLATFORM_* macros
Issue: LINCD-8360

The mesa-demos-8.4.0 uses the EGL_PLATFORM_* macros and these macros are
declared in the eglext.h which version is higher than 24567 because of
commit 38848b621737 ("egl: Update to revision 24567 of eglext.h") in
https://gitlab.freedesktop.org/mesa/mesa.git.

But the version of eglext.h which provided by libmali-xlnx is 21116 and
no EGL_PLATFORM_* definition there. So revert the 2 commits
7a0f0310a9b5 ("eglinfo: Add EXT_platform_* awareness") and
164487d7b3a0 ("eglinfo: Learn about EGL_EXT_platform_device") to make
eglinfo.c fall back to older version.

This is to fix the build error as below when bitbake mesa-demos.

| ../../../../mesa-demos-8.4.0/src/egl/opengl/eglinfo.c: In function 'main':
| ../../../../mesa-demos-8.4.0/src/egl/opengl/eglinfo.c:224:51: error: 'EGL_PLATFORM_GBM_MESA' undeclared (first use in this function); did you mean 'EGL_PLATFORM_GBM_KHR'?
|   224 |            ret += doOneDisplay(getPlatformDisplay(EGL_PLATFORM_GBM_MESA,
|       |                                                   ^~~~~~~~~~~~~~~~~~~~~
|       |                                                   EGL_PLATFORM_GBM_KHR
| ../../../../mesa-demos-8.4.0/src/egl/opengl/eglinfo.c:224:51: note: each undeclared identifier is reported only once for each function it appears in
| ../../../../mesa-demos-8.4.0/src/egl/opengl/eglinfo.c:229:51: error: 'EGL_PLATFORM_WAYLAND_EXT' undeclared (first use in this function); did you mean 'EGL_PLATFORM_WAYLAND_KHR'?
|   229 |            ret += doOneDisplay(getPlatformDisplay(EGL_PLATFORM_WAYLAND_EXT,
|       |                                                   ^~~~~~~~~~~~~~~~~~~~~~~~
|       |                                                   EGL_PLATFORM_WAYLAND_KHR
| ../../../../mesa-demos-8.4.0/src/egl/opengl/eglinfo.c:234:51: error: 'EGL_PLATFORM_X11_EXT' undeclared (first use in this function); did you mean 'EGL_PLATFORM_X11_KHR'?
|   234 |            ret += doOneDisplay(getPlatformDisplay(EGL_PLATFORM_X11_EXT,
|       |                                                   ^~~~~~~~~~~~~~~~~~~~
|       |                                                   EGL_PLATFORM_X11_KHR
| ../../../../mesa-demos-8.4.0/src/egl/opengl/eglinfo.c:238:51: error: 'EGL_PLATFORM_DEVICE_EXT' undeclared (first use in this function)
|   238 |            ret += doOneDisplay(getPlatformDisplay(EGL_PLATFORM_DEVICE_EXT,
|       |                                                   ^~~~~~~~~~~~~~~~~~~~~~~
| Makefile:595: recipe for target 'eglinfo.o' failed

(LOCAL REV: NOT UPSTREAM) -- sent to meta-xilinx on 20200718

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>